import { createStore } from "vuex";

const ridingClasses = {
  "CLASS 1": "INTRODUCTORY EQUITATION",
  "CLASS 2A": "PRE-NOVICE EQUITATION",
  "CLASS 2B": "NOVICE EQUITATION",
  "CLASS 3": "LIMIT EQUITATION ON THE FLAT",
  "CLASS 4": "LIMIT EQUITATION OVER FENCES",
  "CLASS 5": "INTERMEDIATE EQUITATION ON THE FLAT",
  "CLASS 6": "INTERMEDIATE EQUITATION OVER FENCES",
  "CLASS 7": "OPEN EQUITATION ON THE FLAT",
  "CLASS 8": "OPEN EQUITATION OVER FENCES",
  "CLASS 9": "ALUMNI EQUITATION ON THE FLAT",
  "CLASS 10": "ALUMNI EQUITATION OVER FENCES",
  "CLASS 11": "BEGINNER WESTERN HORSEMANSHIP",
  "CLASS 12A": "ROOKIE A WESTERN HORSEMANSHIP",
  "CLASS 12B": "ROOKIE B WESTERN HORSEMANSHIP",
  "CLASS 13": "LEVEL I WESTERN HORSEMANSHIP",
  "CLASS 14": "LEVEL II WESTERN HORSEMANSHIP",
  "CLASS 15": "LEVEL II RANCH RIDING",
  "CLASS 16": "OPEN WESTERN HORSEMANSHIP",
  "CLASS 17": "OPEN REINING",
  "CLASS 18": "ALUMNI WESTERN HORSEMANSHIP",
  "CLASS 19": "ALUMNI RANCH RIDING"
}



const store = createStore({
  state: {
    role: 1,
    numToRole: {
      1: 'user',
      4: 'admin'
    },
    eventsRiders: {},
    eventsHorses: {},
    eventsClasses: {},
    eventInfo: {},
    classToName: ridingClasses
  }
});

export default function () {
  return store
}

export { store }
